### PR TITLE
Revert "docs: pin the prerequisite link to release-1.0 (#102)"

### PR DESCRIPTION
**Pull request by alebedev87**
This reverts commit 58596f0dfe9b7a29bfd5c6547f065e07178c565c. Wrong target branch for PR#102, should have been `release-1.0`, not `main`.

### CODE REVIEW

**Comment by gcs278** [comment]
Whoops, sorry, I missed this too.
/lgtm
/approve

**Comment by alebedev87** [comment]
/override "test e2e-aws-rosa-operator"

Cluster creation fails at different stages, completely unrelated to the link change.

**Comment by alebedev87** [comment]
/override "ci/prow/e2e-aws-rosa-operator"

Cluster creation fails at different stages, completely unrelated to the PR change (link update).

**Pull request merged**
