### PR TITLE
NE-1380: stable-v1.1 channel

### PR DESCRIPTION
**Pull request by alebedev87**
Adding a new OLM channel for the upcoming `1.1` release.

### CODE REVIEW

**Comment by gcs278** [comment]
Seems straightforward, thanks
/approve
/lgtm

**Comment by alebedev87** [comment]
/test e2e-aws-proxy-operator 

Didn't finish in time, may be the global timeout needs an adjustment.

**Comment by alebedev87** [comment]
/override e2e-aws-proxy-operator

WAF e2e tests took 3 times the usual time and didn't let the last test pass. Taking into account the previous test failed on the WAF case - something is going on in AWS with the WAFs. All the other test passed which gives a high confidence.

**Pull request merged**
